# config/ingestion.yaml

sinan:
  cnes_id: "None"
  cod_uf: "None"
  cod_ibge: "None"
  disease: "DENG"
  start_date: "2013-01-01"
  end_date: "2023-12-31"
  years: 
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
    - 2018
    - 2019
    - 2020
    - 2021
    - 2022
    - 2023

cnes:
  state_code: "RJ"
  file_code: "2401"
  tipo: "ST"
